### ISSUE TITLE
Detalhes do produto

### ISSUE THREAD

**Issue by joaosena19** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2021-2-e2-proj-int-t3-ecoffe-cafenine#34]
Seguir o modelo 
https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2021-2-e2-proj-int-t3-ecoffe-cafenine/blob/main/docs/img/FinalCompra.png
Se o usuário tentar comprar sem estar logado, redireciona pra tela de login

**Comment by YuriWiter-dev** [comment]
Inicie
